name: "Emil Soman"
description: "Coder, artist, guitarist, GardenCityRubyConf organizer"

author: "Emil Soman"

url: "http://www.emilsoman.com"
twitter: emilsoman
email: emil.soman@gmail.com
github: emilsoman
work_name: Codemancers
work_url: http://www.codemancers.com

markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
pygments: true

# Google Analytics
ga_domain: www.emilsoman.com
ga_tracking_id: UA-36099649-1

disqus_shortname: emilsoman

exclude: [Gemfile, Gemfile.lock, README.md]

markdown: redcarpet
